baseURL = "https://grahambrown11.com/"
languageCode = "en-gb"
title = "Graham Brown"
publishDir = "docs"
theme = "gb"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.googleAnalytics]
    id = 'G-ZRRYX04SYY'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -120

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -110

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = -100
